version: 5.5.0.4
type: common
authorName: "Ilya I"
moduleName: "AvaTax Statuses"
description: "This module allows transactions to be set as 'Committed' on custom order statuses."
minorRequiredCoreVersion: 0
dependsOn:
  - XC-AvaTax
  - XC-CustomOrderStatuses
incompatibleWith: {}
showSettingsForm: true
canDisable: true
